### ISSUE TITLE
output

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-audlexdec#2]
correct_response (in toekomst dus graag hernoemen naar expected_answer) heeft geen waarde als waarde FALSE zou moeten zijn. 

verder: als je geen (of te laat) antwoord geeft, wordt de waarde bij 'correct' FALSE. maar dat moet natuurlijk NA zijn, of een andere waarde waaraan je kunt zien dat er geen antwoord is gegeven (-9999, -1, whatever).

deze twee dingen gelden voor alle ld-templates, zo te zien.

kan dit beter geprogrammeerd worden, of komt het door hoe jspsych werkt? je kunt er wel omheen werken natuurlijk (je kunt zien of er op een knop gedrukt is etc), maar echt netjes/kloppend is het allebei niet.

**Comment by jcvanelst** [comment]
de standaard van een trial met een fixed response_timeout-interval (2000 ms) is dat er dan niet de gewenste response is gegeven en is wel behoorlijk 'standaard' qua scoring zoals in de jspsych voorbeelden.

```javascript
        let present_word = {
            type: 'audio-keyboard-response',
            stimulus: jsPsych.timelineVariable('filename'),
            choices: present_word_choices,
            prompt: "",
            trial_ends_after_audio: false,
            trial_duration: RESPONSE_TIMEOUT_DURATION,//<-----------deze dus
            post_trial_gap: DEFAULT_ITI,
            response_ends_trial: true, 
            //(.... etc)

Persoonlijk vind ik het wel netjes dat alle data in de output staat die duidelijk laat zien dat er geen response is gegeven, maar het kan anders: de vraag is logisch gezien niet correct (binaire vraag) beantwoord als er niet is gedrukt, en in de output kom je dan tegen:

```
	{
		"rt": null,
		"stimulus": "./sounds/palve.wav",
		"key_press": null,
		"condition": "PRACTICE",
		"word": "palve",
		"filename": "./sounds/palve.wav",
		"id": 1,
		"trial_phase": "present_word",
		"useful_data_flag": true,
		"correct_response": 0,
		"trial_type": "audio-keyboard-response",
		"trial_index": 13,
		"time_elapsed": 62142,
		"internal_node_id": "0.0-9.0-1.0",
		"subject": "u8zawkpp",
		"list": "my_one_and_only_list",
		"correct": false,
		"key_chosen_ascii": null,
		"key_chosen_char": "\u0000",
		"yes_key": "A",
		"no_key": "L"
	},
```

waarbij geld dat geen toets levert: 		"key_chosen_char": "\u0000"
en de "vertaling": 		"key_chosen_ascii": null (oftewel, niets)

Als je zoiets zou willen als een niet-binaire manier van scoring, dan zou de scoring zoals in elke present_word nu zoals hier:

```javascript
            //...
            on_finish: function(data){
                let convertToKeyCode = jsPsych.pluginAPI.convertKeyCharacterToKeyCode
                
                let correct_key = getCorrectKey()
                let incorrect_key = getIncorrectKey();
                let answer;
                let correct;
                
                // now, if this is the first time, we should set the keyboard exp vars
                if ( yes_key == undefined ){
                    yes_key = correct_key;
                }
                if ( no_key == undefined ){
                    no_key = incorrect_key;
                }
                let key_chosen_ascii = data.key_press;
                let key_chosen_char = upperCaseFromASCII(key_chosen_ascii);
                
                if (key_chosen_char == yes_key){
                    answer = 1;
                } else if (key_chosen_char == no_key){
                    answer = 0;
                } else { 
                    answer = undefined;
                };
                correct = answer == data.correct_response; //<---binaire variabele: de waarde is precies hetzelfde als het correcte antwoord, OF niet)
                data.correct = correct;
                data.key_chosen_ascii = key_chosen_ascii;
                data.key_chosen_char = key_chosen_char;
                data.yes_key = yes_key;
                data.no_key = no_key;
            }
        };
```

Als je zoiets zou willen als een niet-binaire manier van scoring, dan zou de scoring apart moeten worden vormgegeven voor of er wel is gedrukt of niet, wat zeker kan, maar niet erg jspsych-ig en niet erg logisch is, als je het mij vraagt.

**Comment by irisopgithub** [comment]
ok, als het niet jspsych-ig is dan laten we het zo, maar dan zou het m.i. wel in de specifieke documentatie moeten; dat false kan betekenen: geen respons, te late respons, of fout antwoord.

wbt niet logisch: het is een presuppositieschending: de waarheidswaarde van 'de koning van frankrijk is kaal' is niet 'onwaar/fout', het is 'ongedefinieerd' (want de presuppositie 'er is een koning van frankrijk' wordt geschonden). als er geen antwoord is gegeven, is het niet zo dat het foute antwoord is gegeven; er is gewoon geen antwoord gegeven, en dus is de juistheid van het antwoord onbepaald. er zijn ongetwijfeld logica's waarin het anders werkt en de whw van een propositie met een presuppositieschending erin 'fout' danwel 'paars vierkantje met groene stippen' is, maar dit is wel een beetje de standaardlogica vziw, of iig de logica die het dichtst ligt bij hoe het in natuurlijke taal werkt (en dus het meest intuitief voor de gewone mens).

**Comment by maartenuni** [comment]
@irisopgithub is dit issue nog steeds relevant?

**Comment by maartenuni** [comment]
https://github.com/UiL-OTS-labs/jspsych-vislexdec-vp/issues/31
